try:
    print(1 + 'st try')
    
except:
    print('Uma exceção')